CompileFlags:
  Remove:
    - -mfix-esp32-psram-cache-issue
    - -mlongcalls
    - -fstrict-volatile-bitfields
    - -fno-tree-switch-conversion
  Add:
    - -w
    - -Wno-everything
    - -isystem
    - ${platformio_core_dir}/packages/toolchain-xtensa-esp32s3/xtensa-esp32s3-elf/include
    - -isystem
    - ${platformio_core_dir}/packages/framework-arduinoespressif32/tools/sdk/esp32s3/include

Diagnostics:
  UnusedIncludes: Suppress
  MissingIncludes: Suppress
  ClangTidy: []
  SystemHeaders: Suppress

InlayHints:
  Enabled: No

